package com.example.lazycolum

val messages: List<MyMessage> = listOf(
    MyMessage(title = "Título 1",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 2",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 3",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 4",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 5",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 6",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 7",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 8",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 9",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 10",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 11",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
    MyMessage(title = "Título 12",
        body = "You can think of Modifiers as implementations of the decorator pattern"),
)
